apiVersion:  apps/v1
kind: Deployment
metadata:
  name: wordpress-mysql
  namespace: wordpress
  labels:
    app: wordpress-mysql
    tier: backend
spec:
  selector:
    matchLabels:
      app: wordpress-mysql
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress-mysql
        tier: backend
    spec:
      containers:
      - image: mysql:5.7
        args:
          - "--ignore-db-dir=lost+found"
        name: wordpress-mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-mysql-root-secret        
              key: password
        - name: MYSQL_DATABASE
          value: wordpress
        - name: MYSQL_USER
          value: wordpress
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-mysql-secret
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: wordpress-mysql-pvc
          mountPath: "/var/lib/mysql"
      volumes:
      - name: wordpress-mysql-pvc    
        persistentVolumeClaim:
          claimName: wordpress-mysql-pvc