apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  namespace: wordpress
  labels:                 
    app: wordpress-myslq
    tier: backend
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress-mysql
    tier: backend